feat: add koa and eslint
projector-course/video-service pull request #1
Opened 2021-11-04 20:55 UTC by mykhailo-vaskivnyuk

2021-11-05 12:05 UTC, welikoiwanenko commented on README.md
> +⏰ **Deadline: 05/11/2021 22:00**
Это лишнее)

2021-11-05 12:17 UTC, welikoiwanenko requested changes
Выглядит круто🔥
Есть пара мелочей, которые нужно исправить - это дебаг-логи, а также отсутствие необходимых для конвертации папок (store и tmp). Есть 2 пути:
1) Проверять наличие папок средствами fs и создавать, если их нет
2) Создать папки в репе и положить в них пустой файл .gitkeep

2021-11-05 12:17 UTC, welikoiwanenko commented on src/api/controllers/convert_video.js
> +console.log('PATH TO FFMPEG:', FFpath);
Дебаг-консоли нужно убирать

2021-11-05 12:17 UTC, welikoiwanenko commented on src/index.js
> +  .listen(PORT, () => console.log(`Server is running on ${BASE_URL}`));
🔥🔥🔥🔥🔥🔥🔥🔥

2021-11-05 19:46 UTC, mykhailo-vaskivnyuk commented
поправив

2021-11-05 20:48 UTC, welikoiwanenko requested changes
Нашёл ещё парочку штук, которые стоит исправить.
Также очень рекомендую поправить имена файлов - сделать их в camelCase, ибо так ты их используешь в коде.

2021-11-05 20:48 UTC, welikoiwanenko commented on src/api/controllers/prepare_server.js
> +module.exports = { prepareServer };
Не путай понятия контроллера (который вызывается при взаимодействии с клиентом) с вещами, которые происходят на старте

2021-11-05 20:48 UTC, welikoiwanenko commented on src/api/router.js
> +  .get('/:video_name', getVideo);
Эти 3 функции (getVideoList, uploadVideo, getVideo) должны быть контроллерами
prepareServer - это явно utils/helpers, convertVideo - worker (или service)

2021-11-06 08:36 UTC, mykhailo-vaskivnyuk commented
створив папки utils та services. config в src??

2021-11-06 12:39 UTC, welikoiwanenko commented
config не совсем src, но об этом потом, пускай там побудет пока:)

2021-11-08 16:12 UTC, welikoiwanenko approved these changes

2021-11-08 16:13 UTC, merged